[package]
name = "sqlite_module"
version = "0.1.0"
edition = "2021"

[dependencies]
netconsd_module = {path = "../module"}
once_cell = "1.15.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
anyhow = "1.0.66"